service: ArduinoPushNotification

provider:
  name: aws
  runtime: nodejs10.x

  #  stage: dev
  #  region: us-east-1

  environment:
    DYNAMODB_TABLE: ${self:service}
  #    FIREBASE_AUTHORIZATION: "key=<your legacy firebase cloud messaging server key>"

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
    - Effect: Allow
      Action:
        - dynamodb:Query
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}/index/DeviceToken-index"

functions:
  registrationPost:
    handler: src/registrationPost.handler
    events:
      - http:
          path: registration
          method: post
  registrationPut:
    handler: src/registrationPut.handler
    events:
      - http:
          path: registration/{installationId}
          method: put
  registrationDelete:
    handler: src/registrationDelete.handler
    events:
      - http:
          path: registration/{installationId}
          method: delete
  send:
    handler: src/send.handler
    events:
      - http:
          path: send/
          method: post
      - http:
          path: send/
          method: get

resources:
  Resources:
    ArduinoPushNotification:
      Type: 'AWS::DynamoDB::Table'
      #      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: InstallationId
            AttributeType: S
          - AttributeName: DeviceToken
            AttributeType: S
        KeySchema:
          - AttributeName: InstallationId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: DeviceToken-index
            KeySchema:
              - AttributeName: DeviceToken
                KeyType: HASH
            Projection:
              NonKeyAttributes:
                - InstallationId
              ProjectionType: INCLUDE
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}

#    CloudFrontDistribution:
#      Type: AWS::CloudFront::Distribution
#      Properties:
#        DistributionConfig:
#          Comment: My first CloudFront Distribution
#          DefaultCacheBehavior:
#            TargetOriginId: MyFirstOrigin
#            ViewerProtocolPolicy: 'http-and-https'
#            DefaultTTL: 30
#            ForwardedValues:
#              QueryString: true
#          Enabled: true
#          Origins:
#            - Id: MyFirstOrigin
#              DomainName: hjx6i5lknd.execute-api.us-east-1.amazonaws.com/dev
#              OriginPath: /dev
#              CustomOriginConfig:
#                HTTPPort: 80
#                HTTPSPort: 443
#                OriginProtocolPolicy: https-only
